#! /bin/bash

# ----- Variables

FILENAMES=()
FILENAME=""
URLS=()
#NAMES="const YT_VIDEOS = {"
SCENE_NAMES="const YT_SCENES = ["
#TAG="}; export default YT_VIDEOS;"
SCENES_TAG="]; export default YT_SCENES;"
COUNT=1

cd src/main/webapp/ui/baca-final-ui/src/videos


# ----- Set Progress Message

echo "const PROGRESS_MESSAGE = \"Analyzing YouTube Scenes...\"; export default PROGRESS_MESSAGE;" > ./progress.js;

# ----- Run Scene Detect


while read line;
do

if [[ $line != "*" ]] && [[ $line != "" ]];
then
scenedetect -i YouTube/$line detect-adaptive --threshold 27 split-video -o YouTube/scenes_$line
fi

SCENE_NAMES+="{"

if [ "$(/bin/ls ./YouTube/scenes_$line)" ]; 
then

for FILE in YouTube/scenes_$line/*; 
do
SCENE_NAMES+="scene$COUNT: require('./YouTube/scenes_$line/$(/usr/bin/basename $FILE)'),"
COUNT=$((COUNT+1))
done
fi

SCENE_NAMES+="},"


done<yt_filenames.txt

echo $SCENE_NAMES$SCENES_TAG > ytscenes.js

echo "const PROGRESS_MESSAGE = \"\"; export default PROGRESS_MESSAGE;" > ./progress.js;




