#! /bin/bash

# $1 is number of results
# $2 is search term
# $3 is max file size

# ----- Variables

FILENAMES=()
FILENAME=""
URLS=()
NAMES_TAG="const YT_VIDEOS = {"
NAMES=""
SCENE_NAMES="const YT_SCENES = ["
TAG="}; export default YT_VIDEOS;"
SCENES_TAG="]; export default YT_SCENES;"
COUNT=1

cd src/main/webapp/ui/baca-final-ui/src/videos/YouTube

# ----- Set Progress Message

echo "const PROGRESS_MESSAGE = \"Downloading YouTube Videos...\"; export default PROGRESS_MESSAGE;" > ../progress.js;


# ----- Collect URLs from ytsearch

URLS+=$(yt-dlp --print webpage_url "ytsearch$1:$2" --match-filter !is_live)


# ----- Download each video

for URL in $URLS
do

COUNT=1
NAMES=""
yt-dlp --max-filesize $3 -o "%(id)s.%(ext)s" -f mp4 $URL


# ----- Add filenames to React index file

if [ "$(/bin/ls ../YouTube)" ]; 
then
	for FILE in *;
		do
			echo $FILE >> ../yt_filenames.txt
			NAMES+="video$COUNT: require('./YouTube/$FILE')," 
			COUNT=$((COUNT+1))
			echo $NAMES_TAG$NAMES$TAG > ../ytvids.js
		done
fi
done

echo "const PROGRESS_MESSAGE = \"\"; export default PROGRESS_MESSAGE;" > ../progress.js;








